import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
} from 'react-native';
import { useTheme } from '@/src/context/ThemeContext';

export default function PrivacyPolicyScreen() {
  const { isDark } = useTheme();

  const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
    <View style={styles.section}>
      <Text style={[styles.sectionTitle, { color: isDark ? '#f9fafb' : '#111827' }]}>
        {title}
      </Text>
      {children}
    </View>
  );

  const Paragraph = ({ children }: { children: React.ReactNode }) => (
    <Text style={[styles.paragraph, { color: isDark ? '#d1d5db' : '#374151' }]}>
      {children}
    </Text>
  );

  const BulletPoint = ({ children }: { children: React.ReactNode }) => (
    <View style={styles.bulletContainer}>
      <Text style={[styles.bullet, { color: isDark ? '#d1d5db' : '#374151' }]}>•</Text>
      <Text style={[styles.bulletText, { color: isDark ? '#d1d5db' : '#374151' }]}>
        {children}
      </Text>
    </View>
  );

  return (
    <ScrollView
      style={[styles.container, { backgroundColor: isDark ? '#111827' : '#f9fafb' }]}
      contentContainerStyle={styles.content}
    >
      <View style={styles.header}>
        <Text style={[styles.title, { color: isDark ? '#f9fafb' : '#111827' }]}>
          Privacy Policy
        </Text>
        <Text style={[styles.lastUpdated, { color: isDark ? '#9ca3af' : '#6b7280' }]}>
          Last Updated: November 25, 2025
        </Text>
        <Text style={[styles.version, { color: isDark ? '#9ca3af' : '#6b7280' }]}>
          Version 1.1.0
        </Text>
      </View>

      <Section title="1. Introduction">
        <Paragraph>
          Business Manager Pro ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile and web application.
        </Paragraph>
      </Section>

      <Section title="2. Information We Collect">
        <Paragraph>
          2.1. Personal Information:
        </Paragraph>
        <BulletPoint>Full name</BulletPoint>
        <BulletPoint>Email address</BulletPoint>
        <BulletPoint>Phone number</BulletPoint>
        <BulletPoint>Physical address</BulletPoint>
        <BulletPoint>Profile picture/avatar</BulletPoint>
        <Paragraph>
          2.2. Business Information:
        </Paragraph>
        <BulletPoint>Business name and logo</BulletPoint>
        <BulletPoint>Product catalogs and inventory data</BulletPoint>
        <BulletPoint>Customer information and contact details</BulletPoint>
        <BulletPoint>Sales records and transaction history</BulletPoint>
        <BulletPoint>Expense records and categories</BulletPoint>
        <BulletPoint>Team member information and roles</BulletPoint>
        <Paragraph>
          2.3. Technical Information:
        </Paragraph>
        <BulletPoint>Device information and identifiers</BulletPoint>
        <BulletPoint>IP address and location data</BulletPoint>
        <BulletPoint>Usage patterns and analytics</BulletPoint>
        <BulletPoint>Session information and authentication tokens</BulletPoint>
      </Section>

      <Section title="3. How We Collect Information">
        <Paragraph>
          3.1. Direct Collection: Information you provide when creating an account, updating your profile, or using Application features.
        </Paragraph>
        <Paragraph>
          3.2. Automated Collection: Technical data collected automatically through cookies, device sensors, and usage tracking.
        </Paragraph>
        <Paragraph>
          3.3. Camera and File Access: Images captured or selected for products, business logos, and user avatars.
        </Paragraph>
      </Section>

      <Section title="4. How We Use Your Information">
        <Paragraph>
          We use collected information to:
        </Paragraph>
        <BulletPoint>Provide and maintain Application services</BulletPoint>
        <BulletPoint>Process your business transactions and operations</BulletPoint>
        <BulletPoint>Generate reports and analytics for your business (informational purposes only, not for compliance or official use)</BulletPoint>
        <BulletPoint>Authenticate users and maintain security</BulletPoint>
        <BulletPoint>Improve Application features and user experience</BulletPoint>
        <BulletPoint>Communicate updates and important information</BulletPoint>
        <BulletPoint>Comply with legal obligations</BulletPoint>
      </Section>

      <Section title="5. Important Disclaimer: Reports and Analytics">
        <Paragraph>
          5.1. Nature of Reports: All reports, financial summaries, income statements, cash flow analyses, profit calculations, and any analytics generated by the Application are intended solely for your basic business understanding and informational purposes.
        </Paragraph>
        <Paragraph>
          5.2. Not Certified or Audited: The reports and data provided are NOT:
        </Paragraph>
        <BulletPoint>Certified financial statements</BulletPoint>
        <BulletPoint>Audited financial reports</BulletPoint>
        <BulletPoint>Tax-compliant documents</BulletPoint>
        <BulletPoint>Regulatory compliance reports</BulletPoint>
        <BulletPoint>Official accounting records for legal purposes</BulletPoint>
        <BulletPoint>Suitable for government submissions or legal proceedings</BulletPoint>
        <Paragraph>
          5.3. Professional Advice Required: The Application does not provide accounting, tax, legal, or financial advice. You must consult qualified professionals (CPAs, tax advisors, accountants, legal counsel) for all compliance, reporting, and regulatory matters.
        </Paragraph>
        <Paragraph>
          5.4. Data Accuracy Limitation: While we process your data as entered, we do not verify, audit, or guarantee the accuracy of calculations, reports, or analytics. You are responsible for verifying all information and ensuring it meets your business and legal requirements.
        </Paragraph>
        <Paragraph>
          5.5. No Liability for Business Use: We are not liable for any business, tax, legal, or financial consequences arising from your use or reliance on the reports and analytics generated by the Application.
        </Paragraph>
      </Section>

      <Section title="6. Data Storage and Security">
        <Paragraph>
          6.1. Storage Infrastructure: Your data is stored securely using Supabase cloud infrastructure with enterprise-grade security measures.
        </Paragraph>
        <Paragraph>
          6.2. Encryption: Data is encrypted in transit using TLS/SSL protocols and at rest using industry-standard encryption.
        </Paragraph>
        <Paragraph>
          6.3. Row Level Security: Database access is controlled through Row Level Security (RLS) ensuring users can only access authorized business data.
        </Paragraph>
        <Paragraph>
          6.4. Session Management: User sessions expire after one week of inactivity to protect unauthorized access.
        </Paragraph>
        <Paragraph>
          6.5. Authentication: We use Supabase Auth with secure password hashing and token-based authentication.
        </Paragraph>
      </Section>

      <Section title="7. Data Isolation and Multi-Tenancy">
        <Paragraph>
          7.1. Business Isolation: Each business operates as a separate tenant with isolated data. Users cannot access data from businesses they are not authorized to view.
        </Paragraph>
        <Paragraph>
          7.2. Role-Based Access: Access to business data is controlled by user roles (Admin, Staff) with different permission levels.
        </Paragraph>
        <Paragraph>
          7.3. Cross-Business Security: Even if you belong to multiple businesses, data from one business cannot be accessed when working in another.
        </Paragraph>
      </Section>

      <Section title="8. Data Sharing and Disclosure">
        <Paragraph>
          8.1. We DO NOT sell your personal or business data to third parties.
        </Paragraph>
        <Paragraph>
          8.2. We may share information with:
        </Paragraph>
        <BulletPoint>Supabase (our infrastructure provider) for hosting and authentication</BulletPoint>
        <BulletPoint>Team members within your authorized businesses</BulletPoint>
        <BulletPoint>Legal authorities when required by law</BulletPoint>
        <Paragraph>
          8.3. Business Transfers: In case of merger, acquisition, or sale, your information may be transferred to the new entity.
        </Paragraph>
      </Section>

      <Section title="9. Your Privacy Rights">
        <Paragraph>
          You have the right to:
        </Paragraph>
        <BulletPoint>Access your personal data</BulletPoint>
        <BulletPoint>Correct inaccurate information</BulletPoint>
        <BulletPoint>Delete your account and data</BulletPoint>
        <BulletPoint>Export your business data</BulletPoint>
        <BulletPoint>Opt-out of non-essential communications</BulletPoint>
        <BulletPoint>Withdraw consent for data processing</BulletPoint>
        <Paragraph>
          9.1. Right to Delete Your Data: We provide two types of data deletion to respect your privacy rights:
        </Paragraph>
        <Paragraph>
          9.2. Business Deletion: You can delete individual businesses you own. This permanently removes all business data including sales, customers, products, expenses, team member associations, and uploaded files. Business deletion is immediate, irreversible, and affects all team members who will lose access. Only business owners can delete businesses.
        </Paragraph>
        <Paragraph>
          9.3. Account Deletion: You can permanently delete your entire account. This requires first deleting all businesses you own, then removes your user profile, authentication credentials, and all personal data. Account deletion is immediate and irreversible with no recovery or reactivation possible.
        </Paragraph>
        <Paragraph>
          9.4. Pre-Deletion Recommendations: Before deleting any data, we strongly recommend:
        </Paragraph>
        <BulletPoint>Export all critical business data using our export features</BulletPoint>
        <BulletPoint>Download financial reports and analytics</BulletPoint>
        <BulletPoint>Save customer contact information separately</BulletPoint>
        <BulletPoint>Backup product catalogs and inventory records</BulletPoint>
        <BulletPoint>Notify team members of planned business deletion</BulletPoint>
        <BulletPoint>Review legal data retention requirements for your jurisdiction</BulletPoint>
        <BulletPoint>Consult tax and legal professionals if required</BulletPoint>
        <Paragraph>
          9.5. Deletion Limitations: We cannot delete certain data in specific circumstances:
        </Paragraph>
        <BulletPoint>Data subject to legal hold or court order</BulletPoint>
        <BulletPoint>Records required for regulatory compliance</BulletPoint>
        <BulletPoint>Anonymized analytics data (no personal identifiers)</BulletPoint>
        <BulletPoint>Data needed for active dispute resolution</BulletPoint>
        <BulletPoint>Fraud prevention records as legally required</BulletPoint>
        <Paragraph>
          9.6. How to Request Deletion:
        </Paragraph>
        <BulletPoint>Business Deletion: Settings → Business Settings → Delete Business</BulletPoint>
        <BulletPoint>Account Deletion: Settings → Privacy → Delete Account</BulletPoint>
        <BulletPoint>Both require owner authorization and explicit confirmation</BulletPoint>
        <BulletPoint>Deletion executes immediately upon confirmation</BulletPoint>
      </Section>

      <Section title="10. Data Retention and Deletion">
        <Paragraph>
          10.1. Active Account Retention: We retain your data as long as your account is active and you continue using the Application. There is no automatic deletion of inactive accounts; you must explicitly request account deletion.
        </Paragraph>
        <Paragraph>
          10.2. Business Deletion - Immediate Removal: When you delete a business, all associated data is immediately and permanently deleted from our active database systems. This includes all sales records, customer information, products, expenses, team member associations, notifications, and uploaded files. Deletion is executed using PostgreSQL CASCADE constraints ensuring complete automatic removal of all related data.
        </Paragraph>
        <Paragraph>
          10.3. Account Deletion - Complete Removal: When you delete your account, we permanently remove your user profile, authentication credentials, all owned businesses (and their complete data), your membership in other businesses, uploaded personal files, and application preferences. Your account cannot be recovered or reactivated after deletion.
        </Paragraph>
        <Paragraph>
          10.4. Data Deletion Scope: The following data is permanently deleted during business or account deletion: </Paragraph>
        <BulletPoint>Business information, settings, and configuration</BulletPoint>
        <BulletPoint>Complete sales history and transaction records</BulletPoint>
        <BulletPoint>Customer database and contact information</BulletPoint>
        <BulletPoint>Product catalog, inventory, and stock levels</BulletPoint>
        <BulletPoint>Expense records, categories, and financial data</BulletPoint>
        <BulletPoint>Financial reports, analytics, and insights</BulletPoint>
        <BulletPoint>Team member relationships and permissions</BulletPoint>
        <BulletPoint>Cart data and pending orders</BulletPoint>
        <BulletPoint>All uploaded images, logos, and documents</BulletPoint>
        <BulletPoint>Notification history and preferences</BulletPoint>
        <BulletPoint>User profile and authentication credentials (account deletion)</BulletPoint>
        <Paragraph>
          10.5. Immediate vs Eventual Deletion Timeline:
        </Paragraph>
        <BulletPoint>Primary database records: Deleted immediately (within seconds)</BulletPoint>
        <BulletPoint>Storage files (images, documents): Deletion initiated immediately</BulletPoint>
        <BulletPoint>CDN cached files: May persist up to 7 days until cache expires</BulletPoint>
        <BulletPoint>Database backups: Retained up to 30 days for disaster recovery</BulletPoint>
        <BulletPoint>Analytics logs: Anonymized within 90 days</BulletPoint>
        <Paragraph>
          10.6. Backup Retention Policy: Our infrastructure maintains automated database backups for disaster recovery purposes only. After you delete data, it may remain in backups for up to 30 days before automatic purging. These backups are not accessible to users, staff, or through any recovery service. Backups are solely for system-wide disaster recovery and cannot be used to restore individual user data after deletion.
        </Paragraph>
        <Paragraph>
          10.7. Legal Retention Requirements: In limited circumstances, we may retain certain data longer than our standard retention period when required by law, such as:
        </Paragraph>
        <BulletPoint>Tax records as required by jurisdiction (typically 7 years)</BulletPoint>
        <BulletPoint>Audit trails for fraud prevention and investigation</BulletPoint>
        <BulletPoint>Records subject to court orders or legal holds</BulletPoint>
        <BulletPoint>Data required for active dispute resolution</BulletPoint>
        <BulletPoint>Anonymized data for regulatory compliance reporting</BulletPoint>
        <Paragraph>
          10.8. What We Cannot Delete: Some data cannot be deleted even upon request:
        </Paragraph>
        <BulletPoint>Anonymized analytics data with no personal identifiers</BulletPoint>
        <BulletPoint>Aggregated statistics used for service improvement</BulletPoint>
        <BulletPoint>Data subject to active legal proceedings</BulletPoint>
        <BulletPoint>Records required by law enforcement or regulators</BulletPoint>
        <BulletPoint>Fraud prevention data as legally mandated</BulletPoint>
      </Section>


      <Section title="10A. Data Deletion Process and Guarantees">
        <Paragraph>
          10A.1. Business Deletion Process: Only the business owner can initiate business deletion. The Application displays a comprehensive preview showing all data that will be deleted (sales count, expenses, customers, products, carts, team members). Deletion requires explicit two-factor confirmation to prevent accidental data loss. Once confirmed, deletion executes immediately with no delay or grace period.
        </Paragraph>
        <Paragraph>
          10A.2. Account Deletion Process: Account deletion is initiated from Privacy Settings. The Application shows a preview of all data to be deleted including all owned businesses and their data. You must delete all owned businesses before account deletion can proceed. Final confirmation requires password verification. Deletion executes immediately upon confirmation, permanently removing authentication credentials and user profile.
        </Paragraph>
        <Paragraph>
          10A.3. Automatic CASCADE Deletion: Our database uses PostgreSQL CASCADE constraints to ensure complete data removal. When a business is deleted, all related records (sales, customers, products, expenses, team members, carts, notifications) are automatically deleted in a single atomic transaction. This guarantees no orphaned data remains in the system and ensures complete privacy protection.
        </Paragraph>
        <Paragraph>
          10A.4. Storage File Deletion: All uploaded files (images, logos, documents) are deleted from cloud storage via secure API calls. File deletion is initiated immediately upon business or account deletion. Files are removed from our CDN cache, though cached copies may persist for up to 7 days until global cache purge completes. Permanent deletion is confirmed by our storage provider.
        </Paragraph>
        <Paragraph>
          10A.5. Team Member Notification: When a business is deleted, all team members are automatically notified of the deletion and their removal from the business. Team members' personal accounts and data remain intact; only their association with the deleted business is removed. Team members do not lose access to other businesses they belong to.
        </Paragraph>
        <Paragraph>
          10A.6. Deletion Irreversibility: All deletions are PERMANENT and IRREVERSIBLE. There is no undo option, no grace period, no recovery service, and no way to restore deleted data. Once deletion is confirmed, data is immediately removed from active systems. We strongly recommend exporting all critical data before initiating any deletion.
        </Paragraph>
        <Paragraph>
          10A.7. No Recovery Service: BizManage does not provide data recovery, backup restoration, or any service to retrieve deleted data. While automated backups exist for disaster recovery, they are not accessible to users or staff and cannot be used for individual data restoration. Do not rely on backups for data recovery after deletion.
        </Paragraph>
      </Section>

      <Section title="11. Children's Privacy">
        <Paragraph>
          The Application is not intended for users under 18 years of age. We do not knowingly collect information from children. If we discover we have collected data from a child, we will delete it promptly.
        </Paragraph>
      </Section>

      <Section title="12. International Data Transfers">
        <Paragraph>
          Your data may be transferred to and processed in countries other than your country of residence. We ensure appropriate safeguards are in place to protect your information in accordance with this Privacy Policy.
        </Paragraph>
      </Section>

      <Section title="13. Cookies and Tracking">
        <Paragraph>
          13.1. Essential Cookies: We use cookies for authentication, session management, and Application functionality.
        </Paragraph>
        <Paragraph>
          13.2. Analytics: We may collect anonymous usage data to improve the Application.
        </Paragraph>
        <Paragraph>
          13.3. Local Storage: The Application stores preferences (theme, language) locally on your device.
        </Paragraph>
      </Section>

      <Section title="14. Third-Party Services">
        <Paragraph>
          14.1. Supabase: Our primary infrastructure provider. Review Supabase's privacy policy at https://supabase.com/privacy
        </Paragraph>
        <Paragraph>
          14.2. Device Permissions: The Application requests camera and file access permissions solely for barcode scanning and image uploads.
        </Paragraph>
      </Section>

      <Section title="15. Data Breach Notification">
        <Paragraph>
          In the event of a data breach affecting your personal information, we will notify you and relevant authorities in accordance with applicable laws and regulations.
        </Paragraph>
      </Section>

      <Section title="16. Your Responsibilities">
        <Paragraph>
          You are responsible for:
        </Paragraph>
        <BulletPoint>Maintaining the confidentiality of your account credentials</BulletPoint>
        <BulletPoint>Ensuring the accuracy of information you provide</BulletPoint>
        <BulletPoint>Protecting customer data collected through the Application</BulletPoint>
        <BulletPoint>Complying with applicable data protection laws in your jurisdiction</BulletPoint>
        <BulletPoint>Creating regular backups of your business data</BulletPoint>
        <BulletPoint>Consulting appropriate professionals for all tax, accounting, and legal compliance matters</BulletPoint>
        <BulletPoint>Verifying all reports and calculations before using them for any official purpose</BulletPoint>
        <BulletPoint>Exporting and backing up all critical data before deleting any business or account</BulletPoint>
        <BulletPoint>Understanding legal data retention requirements before initiating deletion</BulletPoint>
      </Section>

      <Section title="17. GDPR Compliance (EU Users)">
        <Paragraph>
          For users in the European Union:
        </Paragraph>
        <BulletPoint>Legal basis for processing: Consent, contract performance, legitimate interests</BulletPoint>
        <BulletPoint>Right to data portability in machine-readable format</BulletPoint>
        <BulletPoint>Right to object to automated decision-making</BulletPoint>
        <BulletPoint>Right to lodge complaints with supervisory authorities</BulletPoint>
        <Paragraph>
          17.1. Right to Erasure (GDPR Article 17): We fully comply with GDPR erasure requirements. Your data is deleted without undue delay upon request. Complete removal from active systems occurs immediately. Database backups are retained for a maximum of 30 days for disaster recovery, after which they are automatically purged. Exceptions apply only for legal compliance obligations, fraud prevention as required by law, or active legal proceedings. There is no charge for deletion requests. Account deletion confirmation is not provided as the account no longer exists after deletion.
        </Paragraph>
      </Section>

      <Section title="18. CCPA Compliance (California Users)">
        <Paragraph>
          For California residents:
        </Paragraph>
        <BulletPoint>Right to know what personal information is collected</BulletPoint>
        <BulletPoint>Right to delete personal information</BulletPoint>
        <BulletPoint>Right to opt-out of sale (we do not sell data)</BulletPoint>
        <BulletPoint>Right to non-discrimination for exercising privacy rights</BulletPoint>
        <Paragraph>
          18.1. Right to Delete Personal Information (CCPA Section 1798.105): All deletion requests are honored free of charge and completed immediately upon confirmation (well within the legally required 45-day maximum). You will not face discrimination for exercising your deletion rights. Exceptions apply only for legal compliance requirements, fraud prevention, and business necessity as defined by CCPA. The deletion scope is clearly communicated before confirmation, and all related data is permanently removed using CASCADE deletion.
        </Paragraph>
      </Section>

      <Section title="19. Changes to Privacy Policy">
        <Paragraph>
          We may update this Privacy Policy periodically. We will notify you of significant changes through the Application or via email. Continued use after changes constitutes acceptance of the updated policy.
        </Paragraph>
      </Section>

      <Section title="20. Contact Information">
        <Paragraph>
          For privacy-related questions, concerns, or to exercise your rights, please contact us through the Application's support channels or by creating an issue in our repository.
        </Paragraph>
      </Section>

      <Section title="21. Consent">
        <Paragraph>
          By using Business Manager Pro, you consent to the collection, use, and processing of your information as described in this Privacy Policy.
        </Paragraph>
      </Section>

      <View style={styles.footer}>
        <Text style={[styles.footerText, { color: isDark ? '#9ca3af' : '#6b7280' }]}>
          Your privacy and data security are our top priorities. We are committed to transparency and protecting your information.
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    padding: 16,
    paddingTop: 60,
    paddingBottom: 40,
  },
  header: {
    marginBottom: 32,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  lastUpdated: {
    fontSize: 14,
    marginBottom: 4,
  },
  version: {
    fontSize: 12,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
    lineHeight: 24,
  },
  paragraph: {
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 12,
  },
  bulletContainer: {
    flexDirection: 'row',
    marginBottom: 8,
    paddingLeft: 8,
  },
  bullet: {
    fontSize: 14,
    marginRight: 8,
    lineHeight: 22,
  },
  bulletText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 22,
  },
  footer: {
    marginTop: 32,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    alignItems: 'center',
  },
  footerText: {
    fontSize: 12,
    textAlign: 'center',
    lineHeight: 18,
  },
});
